export const START_FETCHING_ABOUT_SECTION_1 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_1";
export const FINISH_FETCHING_ABOUT_SECTION_1 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_1";

export const START_FETCHING_ABOUT_SECTION_2 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_2";
export const FINISH_FETCHING_ABOUT_SECTION_2 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_2";

export const START_FETCHING_ABOUT_SECTION_3 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_3";
export const FINISH_FETCHING_ABOUT_SECTION_3 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_3";

export const START_FETCHING_ABOUT_SECTION_4 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_4";
export const FINISH_FETCHING_ABOUT_SECTION_4 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_4";

export const START_FETCHING_ABOUT_SECTION_5 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_5";
export const FINISH_FETCHING_ABOUT_SECTION_5 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_5";

export const START_FETCHING_ABOUT_SECTION_6 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_6";
export const FINISH_FETCHING_ABOUT_SECTION_6 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_6";

export const START_FETCHING_ABOUT_SECTION_7 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/START_FETCHING_SECTION_7";
export const FINISH_FETCHING_ABOUT_SECTION_7 =
  "ADVANCED_VELOCITY/REDUX/ABOUT/ACTION_TYPES/FINISH_FETCHING_SECTION_7";
