export const CHANGE_CONTACT_US_INPUT =
  "ADVANCED_VELOCITY/REDUX/CONTACT_US/CONTACT_US_INPUT";

export const START_CONTACT_US =
  "ADVANCED_VELOCITY/REDUX/CONTACT_US/START_CONTACT_US";
export const FINISH_CONTACT_US =
  "ADVANCED_VELOCITY/REDUX/CONTACT_US/FINISH_CONTACT_US";
