export const START_FETCHING_INTERCOM =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/START_FETCHING_INTERCOM";

export const FINISH_FETCHING_INTERCOM =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/FINISH_FETCHING_INTERCOM";
