export const START_FETCHING_ALL_PORJECTS =
  "ADVANCED_VELOCITY/REDUX/PROJECTS/START_FETCHING_ALL_PROJECTS";
export const FINISH_FETCHING_ALL_PORJECTS =
  "ADVANCED_VELOCITY/REDUX/PROJECTS/FINISH_FETCHING_ALL_PROJECTS";

export const START_FETCH_SPECIFIC_PROJECT =
  "ADVANCED_VELOCITY/REDUX/PROJECTS/START_FETCH_SPECIFIC_PROJECT";
export const FINISH_FETCH_SPECIFIC_PROJECT =
  "ADVANCED_VELOCITY/REDUX/PROJECTS/FINISH_FETCH_SPECIFIC_PROJECT";
