export const START_FETCHING_REQUEST_DEMO =
  "ADVANCED_VELOCITY/REDUX/RD/START_FETCHING_REQUEST_DEMO";
export const FINISH_FETCHING_REQUEST_DEMO =
  "ADVANCED_VELOCITY/REDUX/RD/FINISH_FETCHING_REQUEST_DEMO";

export const START_FETCHING_REQUEST_DEMO_CATEGORIES =
  "ADVANCED_VELOCITY/REDUX/RD/START_FETCHING_REQUEST_DEMO_CATEGORIES";
export const FINISH_FETCHING_REQUEST_DEMO_CATEGORIES =
  "ADVANCED_VELOCITY/REDUX/RD/FINISH_FETCHING_REQUEST_DEMO_CATEGORIES";

export const CHANGE_REQUEST_DEOM =
  "ADVANCED_VELOCITY/REDUX/RD/CHANGE_REQUEST_DEMO";

export const CHANGE_REQUEST_DEOM_CHECK_BOX =
  "ADVANCED_VELOCITY/REDUX/RD/CHANGE_REQUEST_DEOM_CHECK_BOX";

export const START_SENDING_REQUEST_DEMO =
  "ADVANCED_VELOCITY/REDUX/RD/START_SENDING_REQUEST_DEMO";
export const FINISH_SENDING_REQUEST_DEMO =
  "ADVANCED_VELOCITY/REDUX/RD/FINISH_SENDING_REQUEST_DEMO";
