export const START_FETCHING_SMART_CONNECT =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/START_FETCHING_SMART_CONNECT";

export const FINISH_FETCHING_SMART_CONNECT =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/FINISH_FETCHING_SMART_CONNECT";
