export const START_FETCHING_SMART_PARKING =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/START_FETCHING_SMART_PARKING";

export const FINISH_FETCHING_SMART_PARKING =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/FINISH_FETCHING_SMART_PARKING";
