export const START_FETCHING_SUPPORT =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/START_FETCHING_SUPPORT";

export const FINISH_FETCHING_SUPPORT =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/FINISH_FETCHING_SUPPORT";
