export const START_FETCHING_VISITOR_MANAGEMENT_SYSTEM =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/START_FETCHING_SYSTEM";

export const FINISH_FETCHING_VISITOR_MANAGEMENT_SYSTEM =
  "ADVANCED_VELOCITY/REDUX/VISTOR_MS/FINISH_FETCHING_SYSTEM";
