import Head from 'next/head'
import MonitorEnergy from '../components/landing/MonitorEnergy'
import Offer from '../components/landing/Offer'
import OurGlobalPartners from '../components/landing/OurGlobalPartners'
import Para from '../components/landing/Para'
import Solutions from '../components/landing/Solutions'
import Video from '../components/landing/Video'
import WhyChooseUs from '../components/landing/WhyChooseUs'
import axios from "axios";
import {BASE_URL} from "../variable";


export default function Home({data}) {
  return (
    <>

     <Head>
         <title>Advanced Velocity</title>
         <meta name="description" content="Generated by Advanced Velocity" />
         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
 
        <Video data={data[0]} />
        <Para data={data[1]} />
        <Solutions data={data}/>
        <WhyChooseUs data={data} />
        <Offer data={data} />
        <MonitorEnergy  data={data}/>
        <OurGlobalPartners data={data} />
   </>
  )
}
export async function getStaticProps(){
  let data = [];
 



   await axios.get(`${BASE_URL}/posts/landing-page`).then((response) => {
    data = response.data;
  });
 
  return{
    props:{
      data
    }
  }
}